version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    command: gunicorn fastams.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/home/fastams/app/static
      - assets_volume:/home/fastams/app/assets
      - logs_volume:/home/fastams/app/logs
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - 5433:5432
  redis:
    image: "redis:alpine"
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/fastams/app/static
      - assets_volume:/home/fastams/app/assets
      - logs_volume:/home/fastams/app/logs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  celery:
    build: .
    command: celery -A fastams worker -l info
    restart: always
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data: null
  static_volume: null
  assets_volume: null
  logs_volume: null
